# runs server on Docker Container
# FROM python:3.7.6-slim

# RUN apt-get update \
#     && apt-get install -y --no-install-recommends gcc \
#     && rm -rf /var/lib/apt/lists/* \
#     && pip install --upgrade pip setuptools wheel \
#     && pip install cryptography \
#     && apt-get purge -y --auto-remove gcc
    
# WORKDIR /app

# COPY . /app

# RUN pip3 --no-cache-dir install -r requirements.txt

# EXPOSE 5000

# ENTRYPOINT ["python3"]
# CMD ["code/setupSunPosFlask.py"]

