/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import model3d from './model3d.glb'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(model3d)
  return (
    <group  ref={group} {...props} dispose={null}>
      {/* <mesh castShadow material={nodes.Object037.material} geometry={nodes.Object037.geometry} /> */}
      <mesh castShadow material={materials['TREE_CANOPY']} geometry={nodes['park-trees'].geometry} />
      {/* <mesh castShadow material={materials['TREE_CANOPY']} geometry={nodes['sidestreet-trees'].geometry} /> */}
      <mesh castShadow material={materials.brick} geometry={nodes['1079499001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1079499001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1059980001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1059980001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1059970001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1059970001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1059969001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1059969001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1062264001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1062264001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1062289001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1062289001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1084789001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1084789001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1059979001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1059979001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1062286001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1062286001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1062281001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1062281001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1059967001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1059967001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1062282001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1062282001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1059971001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1059971001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1062287001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1062287001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1062278001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1062278001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1062265001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1062265001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1062280001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1062280001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1062279001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1062279001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1087748001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1087748001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1062277001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1062277001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1059972001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1059972001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1062288001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1062288001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1062283001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1062283001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1059968001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1059968001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1059950001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1059950001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1059973001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1059973001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1059951001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1059951001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1059978001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1059978001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1059974001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1059974001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1059977001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1059977001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1062266001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1062266001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1062291001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1062291001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1062290001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1062290001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1059966001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1059966001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1062276001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1062276001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1079500001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1079500001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['Brep_92c925ec-162a-4fdc-8cf9-70751ebbc011001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['Brep_92c925ec-162a-4fdc-8cf9-70751ebbc011001_1'].geometry} />
      <mesh castShadow material={materials.brick} geometry={nodes['1089583001'].geometry} />
      <mesh castShadow material={materials.rooftop} geometry={nodes['1089583001_1'].geometry} />
      <mesh receiveShadow material={materials.GROUND} geometry={nodes.ground001.geometry} />
      <mesh castShadow material={materials.WATER} geometry={nodes.ground.geometry} />
    </group>
  )
}
