/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'
import { MeshStandardMaterial } from 'three'
import bldg from './broadwaybldg.glb'

export default function Model({ setScene, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF(bldg)

  const highlightMaterial = new MeshStandardMaterial({color: 0xffec00})

  const handleMouseOver = (e) => {
    e.object.material = highlightMaterial
    setScene(2)
  }

  const resetMaterial = (e) => {
    e.object.material = materials['roof-paint']
    setScene(0)
  }

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow material={materials.brick} geometry={nodes.facade.geometry} />
      <mesh castShadow material={materials.glass} geometry={nodes['storefront-window'].geometry} />
      <mesh castShadow material={materials.aluminum} geometry={nodes['ventilation-band'].geometry} />
      <mesh castShadow material={materials['roof-paint']} geometry={nodes.floor.geometry} />
      <mesh
        onPointerOver={handleMouseOver}
        onPointerOut={resetMaterial}
        material={materials['roof-paint']}
        geometry={nodes['roof-bulkhead'].geometry}
        castShadow
      />
      <mesh receiveShadow material={materials['roof-paint']} geometry={nodes.roof.geometry} />
      <mesh castShadow material={materials['roof-paint']} geometry={nodes['roof-balcony'].geometry} />
      <mesh castShadow material={materials.glass} geometry={nodes['windows-upper'].geometry} />
    </group>
  )
}
