/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { MeshStandardMaterial, Color } from 'three'
import solarpanels from './solarpanels.glb';

export default function Model({ setScene }) {
  const group = useRef()
  const { nodes, materials } = useGLTF(solarpanels)

  const highlightMaterial = new MeshStandardMaterial({
    color: new Color(0xffd600),
    emissive: new Color(0xffd600),
    emissiveIntensity: 0.25,
  })

  const applyHighlight = (e) => {
    e.object.material = highlightMaterial
    setScene(1)
  }

  const resetMaterial = (e) => {
    e.object.material = materials.pvPanel
    setScene(0)
  }

  return (
    <group ref={group} dispose={null}>
      <mesh
        castShadow
        onPointerOver={applyHighlight}
        onPointerOut={resetMaterial}
        material={materials.pvPanel}
        geometry={nodes.panel_commercial035.geometry}
        position={[61.06, 60.57, 9.93]}
        rotation={[0.37, 0, 0]}
      />
    </group>
  )
}
