// source: study.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var scenario_pb = require('./scenario_pb.js');
goog.object.extend(proto, scenario_pb);
var site_pb = require('./site_pb.js');
goog.object.extend(proto, site_pb);
var summary_pb = require('./summary_pb.js');
goog.object.extend(proto, summary_pb);
var zoning_lot_pb = require('./zoning_lot_pb.js');
goog.object.extend(proto, zoning_lot_pb);
goog.exportSymbol('proto.Study', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Study = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Study.repeatedFields_, null);
};
goog.inherits(proto.Study, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Study.displayName = 'proto.Study';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Study.repeatedFields_ = [2,3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Study.prototype.toObject = function(opt_includeInstance) {
  return proto.Study.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Study} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Study.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    scenariosList: jspb.Message.toObjectList(msg.getScenariosList(),
    scenario_pb.Scenario.toObject, includeInstance),
    sitesList: jspb.Message.toObjectList(msg.getSitesList(),
    site_pb.Site.toObject, includeInstance),
    zoningLotsList: jspb.Message.toObjectList(msg.getZoningLotsList(),
    zoning_lot_pb.ZoningLot.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Study}
 */
proto.Study.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Study;
  return proto.Study.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Study} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Study}
 */
proto.Study.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = new scenario_pb.Scenario;
      reader.readMessage(value,scenario_pb.Scenario.deserializeBinaryFromReader);
      msg.addScenarios(value);
      break;
    case 3:
      var value = new site_pb.Site;
      reader.readMessage(value,site_pb.Site.deserializeBinaryFromReader);
      msg.addSites(value);
      break;
    case 4:
      var value = new zoning_lot_pb.ZoningLot;
      reader.readMessage(value,zoning_lot_pb.ZoningLot.deserializeBinaryFromReader);
      msg.addZoningLots(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Study.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Study.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Study} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Study.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getScenariosList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      scenario_pb.Scenario.serializeBinaryToWriter
    );
  }
  f = message.getSitesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      site_pb.Site.serializeBinaryToWriter
    );
  }
  f = message.getZoningLotsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      zoning_lot_pb.ZoningLot.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.Study.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Study} returns this
 */
proto.Study.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated Scenario scenarios = 2;
 * @return {!Array<!proto.Scenario>}
 */
proto.Study.prototype.getScenariosList = function() {
  return /** @type{!Array<!proto.Scenario>} */ (
    jspb.Message.getRepeatedWrapperField(this, scenario_pb.Scenario, 2));
};


/**
 * @param {!Array<!proto.Scenario>} value
 * @return {!proto.Study} returns this
*/
proto.Study.prototype.setScenariosList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.Scenario=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Scenario}
 */
proto.Study.prototype.addScenarios = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.Scenario, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Study} returns this
 */
proto.Study.prototype.clearScenariosList = function() {
  return this.setScenariosList([]);
};


/**
 * repeated Site sites = 3;
 * @return {!Array<!proto.Site>}
 */
proto.Study.prototype.getSitesList = function() {
  return /** @type{!Array<!proto.Site>} */ (
    jspb.Message.getRepeatedWrapperField(this, site_pb.Site, 3));
};


/**
 * @param {!Array<!proto.Site>} value
 * @return {!proto.Study} returns this
*/
proto.Study.prototype.setSitesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.Site=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Site}
 */
proto.Study.prototype.addSites = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.Site, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Study} returns this
 */
proto.Study.prototype.clearSitesList = function() {
  return this.setSitesList([]);
};


/**
 * repeated ZoningLot zoning_lots = 4;
 * @return {!Array<!proto.ZoningLot>}
 */
proto.Study.prototype.getZoningLotsList = function() {
  return /** @type{!Array<!proto.ZoningLot>} */ (
    jspb.Message.getRepeatedWrapperField(this, zoning_lot_pb.ZoningLot, 4));
};


/**
 * @param {!Array<!proto.ZoningLot>} value
 * @return {!proto.Study} returns this
*/
proto.Study.prototype.setZoningLotsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.ZoningLot=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ZoningLot}
 */
proto.Study.prototype.addZoningLots = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.ZoningLot, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Study} returns this
 */
proto.Study.prototype.clearZoningLotsList = function() {
  return this.setZoningLotsList([]);
};


goog.object.extend(exports, proto);
