/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export default function Buggy(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Buggy.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[12.1, -8.8, 54.3]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
          <group position={[0.1, 4, 1.55]} rotation={[-Math.PI, 0, 2.36]} scale={[1, 1, 1]}>
            <mesh geometry={nodes.tech_light_p_SOLIDS_1.geometry} material={nodes.tech_light_p_SOLIDS_1.material} />
            <mesh geometry={nodes.tech_light_p_SOLIDS_1_1.geometry} material={nodes.tech_light_p_SOLIDS_1_1.material} />
          </group>
          <mesh geometry={nodes.technic_2_2_l_p_SOLIDS_1.geometry} material={nodes.technic_2_2_l_p_SOLIDS_1.material} />
          <mesh
            geometry={nodes.technic_2_2_l_p_SOLIDS_1_1.geometry}
            material={nodes.technic_2_2_l_p_SOLIDS_1_1.material}
          />
        </group>
        <group position={[44.1, -8.8, 54.3]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
          <group position={[0.1, 4, 1.55]} rotation={[-Math.PI, 0, 2.36]} scale={[1, 1, 1]}>
            <mesh geometry={nodes.tech_light_p_SOLIDS_3.geometry} material={nodes.tech_light_p_SOLIDS_3.material} />
            <mesh geometry={nodes.tech_light_p_SOLIDS_3_1.geometry} material={nodes.tech_light_p_SOLIDS_3_1.material} />
          </group>
          <mesh geometry={nodes.technic_2_2_l_p_SOLIDS_3.geometry} material={nodes.technic_2_2_l_p_SOLIDS_3.material} />
          <mesh
            geometry={nodes.technic_2_2_l_p_SOLIDS_3_1.geometry}
            material={nodes.technic_2_2_l_p_SOLIDS_3_1.material}
          />
        </group>
        <group position={[19.65, -27.8, 31.77]} rotation={[-Math.PI / 2, 0, 1.18]} scale={[1, 1, 1]}>
          <mesh
            geometry={nodes.technic_shaft_x8_SOLIDS_1.geometry}
            material={nodes.technic_shaft_x8_SOLIDS_1.material}
          />
          <mesh
            geometry={nodes.technic_shaft_x8_SOLIDS_1_1.geometry}
            material={nodes.technic_shaft_x8_SOLIDS_1_1.material}
          />
          <mesh
            geometry={nodes.body_76.geometry}
            material={nodes.body_76.material}
            position={[0, -2.27, 25.7]}
            rotation={[Math.PI, 0, 0]}
          />
          <mesh
            geometry={nodes.body_78.geometry}
            material={nodes.body_78.material}
            position={[17.77, -2.27, 56.4]}
            rotation={[0, 0, Math.PI]}
          />
          <mesh
            geometry={nodes.body_79.geometry}
            material={nodes.body_79.material}
            position={[7.75, -10.02, 0]}
            rotation={[0, 0, Math.PI / 2]}
          />
        </group>
        <group position={[15.22, 5.14, 30.13]}>
          <mesh
            geometry={nodes.body_71_instance_1.geometry}
            material={nodes.body_71_instance_1.material}
            position={[8.88, -1.14, 14.05]}
            rotation={[Math.PI, 0, 0]}
          />
          <mesh
            geometry={nodes.body_71_instance_2.geometry}
            material={nodes.body_71_instance_2.material}
            position={[8.88, -1.14, 36.55]}
            rotation={[0, 0, -0.13]}
            scale={[1, 1, 1]}
          />
          <mesh
            geometry={nodes.body_71_instance_3.geometry}
            material={nodes.body_71_instance_3.material}
            position={[8.88, -1.14, 43.75]}
            rotation={[Math.PI, 0, 0]}
          />
          <mesh
            geometry={nodes.body_81.geometry}
            material={nodes.body_81.material}
            position={[10.02, 7.75, 2.95]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh geometry={nodes.body_82.geometry} material={nodes.body_82.material} position={[0, 0, 43.75]} />
          <mesh
            geometry={nodes.technic_shaft_x6_SOLIDS_1.geometry}
            material={nodes.technic_shaft_x6_SOLIDS_1.material}
          />
          <mesh
            geometry={nodes.technic_shaft_x6_SOLIDS_1_1.geometry}
            material={nodes.technic_shaft_x6_SOLIDS_1_1.material}
          />
        </group>
        <group position={[13.55, -51.07, 21.94]}>
          <mesh
            geometry={nodes.body_84.geometry}
            material={nodes.body_84.material}
            position={[2, 7.39, 19.23]}
            rotation={[Math.PI / 6, 0, 0]}
            scale={[1, 1, 1]}
          />
          <mesh
            geometry={nodes.body_86.geometry}
            material={nodes.body_86.material}
            position={[2, 5.51, 22.48]}
            rotation={[-Math.PI / 3, -0.87, Math.PI]}
            scale={[1, 1, 1]}
          />
          <mesh
            geometry={nodes.body_88.geometry}
            material={nodes.body_88.material}
            position={[-1.37, -14.73, 15.67]}
            rotation={[-2.15, 0.9, -0.87]}
            scale={[1, 1, 1]}
          />
          <mesh geometry={nodes.body_90.geometry} material={nodes.body_90.material} position={[10, 5.5, 28.1]} />
          <mesh
            geometry={nodes.body_92.geometry}
            material={nodes.body_92.material}
            position={[10.38, -2.43, 37.47]}
            rotation={[1.22, Math.PI / 2, 0]}
            scale={[1, 1, 1]}
          />
          <mesh
            geometry={nodes.body_94.geometry}
            material={nodes.body_94.material}
            position={[-5.65, -1.25, -1.66]}
            rotation={[-Math.PI / 2, 1.35, 0.09]}
            scale={[1, 1, 1]}
          />
          <mesh
            geometry={nodes.body_96.geometry}
            material={nodes.body_96.material}
            position={[-2.4, -31.16, -14.64]}
            rotation={[-1.22, 0.12, -1.62]}
            scale={[1, 1, 1]}
          />
          <group position={[2, 5.5, 22.5]} rotation={[-Math.PI / 3, 0, 0]} scale={[1, 1, 1]}>
            <mesh
              geometry={nodes.technic_driver_arm_joint_p_SOLIDS_1.geometry}
              material={nodes.technic_driver_arm_joint_p_SOLIDS_1.material}
            />
            <mesh
              geometry={nodes.technic_driver_arm_joint_p_SOLIDS_1_1.geometry}
              material={nodes.technic_driver_arm_joint_p_SOLIDS_1_1.material}
            />
          </group>
          <group position={[-5.94, -2.68, 17.75]} rotation={[1.7, 0.83, 0.3]} scale={[1, 1, 1]}>
            <mesh
              geometry={nodes.technic_driver_arm_joint_p_SOLIDS_1.geometry}
              material={nodes.technic_driver_arm_joint_p_SOLIDS_1.material}
            />
            <mesh
              geometry={nodes.technic_driver_arm_joint_p_SOLIDS_1_1.geometry}
              material={nodes.technic_driver_arm_joint_p_SOLIDS_1_1.material}
            />
          </group>
          <group position={[28.33, 4.33, 28.98]} rotation={[-0.13, -0.55, 2.98]} scale={[1, 1, 1]}>
            <mesh
              geometry={nodes.technic_driver_arm_joint_p_SOLIDS_1.geometry}
              material={nodes.technic_driver_arm_joint_p_SOLIDS_1.material}
            />
            <mesh
              geometry={nodes.technic_driver_arm_joint_p_SOLIDS_1_1.geometry}
              material={nodes.technic_driver_arm_joint_p_SOLIDS_1_1.material}
            />
          </group>
          <group position={[18, 5.5, 22.5]} rotation={[0.17, 0, Math.PI]} scale={[1, 1, 1]}>
            <mesh
              geometry={nodes.technic_driver_arm_joint_p_SOLIDS_5.geometry}
              material={nodes.technic_driver_arm_joint_p_SOLIDS_5.material}
            />
            <mesh
              geometry={nodes.technic_driver_arm_joint_p_SOLIDS_5_1.geometry}
              material={nodes.technic_driver_arm_joint_p_SOLIDS_5_1.material}
            />
          </group>
          <mesh
            geometry={nodes.body_97_instance_0.geometry}
            material={nodes.body_97_instance_0.material}
            position={[18, 5.48, 22.5]}
            rotation={[-2.97, 0.57, 0]}
            scale={[1, 1, 1]}
          />
          <mesh
            geometry={nodes.body_97_instance_1.geometry}
            material={nodes.body_97_instance_1.material}
            position={[-5.93, -2.67, 17.73]}
            rotation={[2.27, -1.03, 0.4]}
            scale={[1, 1, 1]}
          />
          <mesh
            geometry={nodes.body_97_instance_2.geometry}
            material={nodes.body_97_instance_2.material}
            position={[28.33, 4.31, 28.98]}
            rotation={[2.84, 1.06, 0.29]}
            scale={[1, 1, 1]}
          />
          <mesh
            geometry={nodes.body_98_instance_0.geometry}
            material={nodes.body_98_instance_0.material}
            position={[18, 1.78, 21.84]}
            rotation={[-1.4, 0, 0]}
            scale={[1, 1, 1]}
          />
          <mesh
            geometry={nodes.body_98_instance_1.geometry}
            material={nodes.body_98_instance_1.material}
            position={[-5.18, -1.38, 14.23]}
            rotation={[0.35, -0.2, 0.07]}
            scale={[1, 1, 1]}
          />
          <mesh
            geometry={nodes.body_98_instance_2.geometry}
            material={nodes.body_98_instance_2.material}
            position={[27.8, 0.55, 29.16]}
            rotation={[-1.62, 0.14, 0.01]}
            scale={[1, 1, 1]}
          />
          <mesh
            geometry={nodes.body_99.geometry}
            material={nodes.body_99.material}
            position={[18.03, -33.21, -13.6]}
            rotation={[-1.39, -0.21, -1.53]}
            scale={[1, 1, 1]}
          />
          <mesh
            geometry={nodes.body_100.geometry}
            material={nodes.body_100.material}
            position={[34.12, 2.02, 40.45]}
            rotation={[-1.62, 0.14, -2.65]}
            scale={[1, 1, 1]}
          />
          <group position={[10, 5.5, 22.1]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              geometry={nodes.technic_driver_head_p_SOLIDS_1.geometry}
              material={nodes.technic_driver_head_p_SOLIDS_1.material}
            />
            <mesh
              geometry={nodes.technic_driver_head_p_SOLIDS_1_1.geometry}
              material={nodes.technic_driver_head_p_SOLIDS_1_1.material}
            />
            <mesh
              geometry={nodes.technic_driver_head_p_SOLIDS_1_2.geometry}
              material={nodes.technic_driver_head_p_SOLIDS_1_2.material}
            />
          </group>
          <group position={[10, -6.5, 28.6]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
            <mesh
              geometry={nodes.technic_driver_helmet_p_SOLIDS_1.geometry}
              material={nodes.technic_driver_helmet_p_SOLIDS_1.material}
            />
            <mesh
              geometry={nodes.technic_driver_helmet_p_SOLIDS_1_1.geometry}
              material={nodes.technic_driver_helmet_p_SOLIDS_1_1.material}
            />
          </group>
          <group position={[23.5, 0, 30]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh
              geometry={nodes.technic_driver_hip_joint_p_SOLIDS_1.geometry}
              material={nodes.technic_driver_hip_joint_p_SOLIDS_1.material}
            />
            <mesh
              geometry={nodes.technic_driver_hip_joint_p_SOLIDS_1_1.geometry}
              material={nodes.technic_driver_hip_joint_p_SOLIDS_1_1.material}
            />
          </group>
          <group position={[25.38, -30.36, -5.96]} rotation={[1.57, -1.35, 2.79]} scale={[1, 1, 1]}>
            <mesh
              geometry={nodes.technic_driver_shin_p_SOLIDS_1.geometry}
              material={nodes.technic_driver_shin_p_SOLIDS_1.material}
            />
            <mesh
              geometry={nodes.technic_driver_shin_p_SOLIDS_1_1.geometry}
              material={nodes.technic_driver_shin_p_SOLIDS_1_1.material}
            />
          </group>
          <group position={[5.35, -31.99, -5.96]} rotation={[-Math.PI / 2, -1.44, -Math.PI / 9]} scale={[1, 1, 1]}>
            <mesh
              geometry={nodes.technic_driver_shin_p_SOLIDS_3.geometry}
              material={nodes.technic_driver_shin_p_SOLIDS_3.material}
            />
            <mesh
              geometry={nodes.technic_driver_shin_p_SOLIDS_3_1.geometry}
              material={nodes.technic_driver_shin_p_SOLIDS_3_1.material}
            />
          </group>
          <group position={[2.6, 3.82, -1.66]} rotation={[Math.PI / 2, 1.44, -3.05]} scale={[1, 1, 1]}>
            <mesh
              geometry={nodes.technic_driver_thigh_l_p_SOLIDS_1.geometry}
              material={nodes.technic_driver_thigh_l_p_SOLIDS_1.material}
            />
            <mesh
              geometry={nodes.technic_driver_thigh_l_p_SOLIDS_1_1.geometry}
              material={nodes.technic_driver_thigh_l_p_SOLIDS_1_1.material}
            />
          </group>
          <mesh
            geometry={nodes.technic_driver_torso_p_SOLIDS_1.geometry}
            material={nodes.technic_driver_torso_p_SOLIDS_1.material}
          />
          <mesh
            geometry={nodes.technic_driver_torso_p_SOLIDS_1_1.geometry}
            material={nodes.technic_driver_torso_p_SOLIDS_1_1.material}
          />
        </group>
        <group position={[113.22, 9.38, 0]} rotation={[0, 0, Math.PI]}>
          <mesh
            geometry={nodes.body_72_instance_5.geometry}
            material={nodes.body_72_instance_5.material}
            position={[61.07, -23.42, 8.1]}
            rotation={[Math.PI, Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes.body_72_instance_6.geometry}
            material={nodes.body_72_instance_6.material}
            position={[117.17, -23.47, 8.1]}
            rotation={[Math.PI, Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes.body_102.geometry}
            material={nodes.body_102.material}
            position={[81.02, -23.52, 20.08]}
          />
          <mesh geometry={nodes.body_104.geometry} material={nodes.body_104.material} position={[65.02, -38.62, 0]} />
          <mesh
            geometry={nodes.body_106.geometry}
            material={nodes.body_106.material}
            position={[65, -38.62, 4.9]}
            rotation={[0, 0, Math.PI / 2]}
          />
          <mesh
            geometry={nodes.body_107_instance_0.geometry}
            material={nodes.body_107_instance_0.material}
            position={[65.02, -38.62, 12.8]}
          />
          <mesh
            geometry={nodes.body_107_instance_1.geometry}
            material={nodes.body_107_instance_1.material}
            position={[65.02, -23.42, 16.88]}
          />
          <mesh
            geometry={nodes.body_108_instance_0.geometry}
            material={nodes.body_108_instance_0.material}
            position={[121.1, -38.67, 4.9]}
            rotation={[0, 0, Math.PI / 2]}
          />
        </group>
        <group position={[-65.02, -1.38, 0]}>
          <mesh
            geometry={nodes.body_72_instance_7.geometry}
            material={nodes.body_72_instance_7.material}
            position={[61.07, -23.42, 8.1]}
            rotation={[Math.PI, Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes.body_72_instance_8.geometry}
            material={nodes.body_72_instance_8.material}
            position={[117.17, -23.47, 8.1]}
            rotation={[Math.PI, Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes.body_107_instance_2.geometry}
            material={nodes.body_107_instance_2.material}
            position={[65.02, -38.62, 0]}
          />
          <mesh
            geometry={nodes.body_107_instance_3.geometry}
            material={nodes.body_107_instance_3.material}
            position={[65.02, -38.62, 12.8]}
          />
          <mesh
            geometry={nodes.body_107_instance_4.geometry}
            material={nodes.body_107_instance_4.material}
            position={[65.02, -23.42, 16.88]}
          />
          <mesh
            geometry={nodes.body_108_instance_1.geometry}
            material={nodes.body_108_instance_1.material}
            position={[65, -38.62, 4.9]}
            rotation={[0, 0, Math.PI / 2]}
          />
          <mesh
            geometry={nodes.body_108_instance_2.geometry}
            material={nodes.body_108_instance_2.material}
            position={[121.1, -38.67, 4.9]}
            rotation={[0, 0, Math.PI / 2]}
          />
          <mesh
            geometry={nodes.body_109.geometry}
            material={nodes.body_109.material}
            position={[81.02, -23.52, 20.08]}
          />
        </group>
        <group position={[-21.16, 49.83, 4.13]} rotation={[Math.PI, 0, 0]}>
          <mesh
            geometry={nodes.body_72_instance_9.geometry}
            material={nodes.body_72_instance_9.material}
            position={[13.18, 1.78, 0]}
          />
          <mesh
            geometry={nodes.body_111.geometry}
            material={nodes.body_111.material}
            position={[12.48, 1.78, 0]}
            rotation={[Math.PI, 0, Math.PI / 2]}
          />
          <mesh
            geometry={nodes.body_113.geometry}
            material={nodes.body_113.material}
            position={[12.48, 1.78, 0]}
            rotation={[0, 0, Math.PI / 2]}
          />
        </group>
        <group position={[-21.16, -41.78, 4.13]}>
          <mesh
            geometry={nodes.body_72_instance_10.geometry}
            material={nodes.body_72_instance_10.material}
            position={[13.18, 1.78, 0]}
          />
          <mesh
            geometry={nodes.body_114_instance_0.geometry}
            material={nodes.body_114_instance_0.material}
            position={[12.48, 1.78, 0]}
            rotation={[Math.PI, 0, Math.PI / 2]}
          />
          <mesh
            geometry={nodes.body_115_instance_0.geometry}
            material={nodes.body_115_instance_0.material}
            position={[12.48, 1.78, 0]}
            rotation={[0, 0, Math.PI / 2]}
          />
        </group>
        <group position={[69.36, 46.22, 4.13]} rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh
            geometry={nodes.body_72_instance_11.geometry}
            material={nodes.body_72_instance_11.material}
            position={[13.18, 1.78, 0]}
          />
          <mesh
            geometry={nodes.body_114_instance_1.geometry}
            material={nodes.body_114_instance_1.material}
            position={[12.48, 1.78, 0]}
            rotation={[Math.PI, 0, Math.PI / 2]}
          />
          <mesh
            geometry={nodes.body_115_instance_1.geometry}
            material={nodes.body_115_instance_1.material}
            position={[12.48, 1.78, 0]}
            rotation={[0, 0, Math.PI / 2]}
          />
        </group>
        <group position={[69.36, -41.83, 4.13]} rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh
            geometry={nodes.body_72_instance_12.geometry}
            material={nodes.body_72_instance_12.material}
            position={[13.18, 1.78, 0]}
          />
          <mesh
            geometry={nodes.body_114_instance_2.geometry}
            material={nodes.body_114_instance_2.material}
            position={[12.48, 1.78, 0]}
            rotation={[Math.PI, 0, Math.PI / 2]}
          />
          <mesh
            geometry={nodes.body_115_instance_2.geometry}
            material={nodes.body_115_instance_2.material}
            position={[12.48, 1.78, 0]}
            rotation={[0, 0, Math.PI / 2]}
          />
        </group>
        <group position={[-21.2, 2.22, 4.8]}>
          <mesh
            geometry={nodes.body_72_instance_13.geometry}
            material={nodes.body_72_instance_13.material}
            position={[13.18, 1.78, 0]}
          />
          <mesh
            geometry={nodes.body_114_instance_3.geometry}
            material={nodes.body_114_instance_3.material}
            position={[12.48, 1.78, 0]}
            rotation={[Math.PI, 0, Math.PI / 2]}
          />
          <mesh
            geometry={nodes.body_115_instance_3.geometry}
            material={nodes.body_115_instance_3.material}
            position={[12.48, 1.78, 0]}
            rotation={[0, 0, Math.PI / 2]}
          />
        </group>
        <group position={[69.4, 2.22, 4.8]} rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh
            geometry={nodes.body_72_instance_14.geometry}
            material={nodes.body_72_instance_14.material}
            position={[13.18, 1.78, 0]}
          />
          <mesh
            geometry={nodes.body_114_instance_4.geometry}
            material={nodes.body_114_instance_4.material}
            position={[12.48, 1.78, 0]}
            rotation={[Math.PI, 0, Math.PI / 2]}
          />
          <mesh
            geometry={nodes.body_115_instance_4.geometry}
            material={nodes.body_115_instance_4.material}
            position={[12.48, 1.78, 0]}
            rotation={[0, 0, Math.PI / 2]}
          />
        </group>
        <mesh
          geometry={nodes.body_1.geometry}
          material={nodes.body_1.material}
          position={[16, -82.45, 3.9]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.body_3.geometry}
          material={nodes.body_3.material}
          position={[52.72, 3.64, 60.13]}
          rotation={[-3.05, 0, 0]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.body_5.geometry}
          material={nodes.body_5.material}
          position={[22.73, -81.9, 45.29]}
          rotation={[-Math.PI / 6, 0, Math.PI / 2]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.body_7.geometry}
          material={nodes.body_7.material}
          position={[23.87, -76.16, 37.47]}
          rotation={[-Math.PI / 6, 0, Math.PI / 2]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.body_9.geometry}
          material={nodes.body_9.material}
          position={[16.27, -84.39, 23.23]}
          rotation={[2.62, 0, Math.PI / 2]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.body_11.geometry}
          material={nodes.body_11.material}
          position={[16.15, -35.92, 11.2]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.body_13.geometry}
          material={materials.Material_29}
          position={[24.1, 52, 27.2]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.body_15.geometry}
          material={nodes.body_15.material}
          position={[7.98, 4, 56]}
          rotation={[-1.48, 0, 0]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.body_17.geometry}
          material={nodes.body_17.material}
          position={[59.52, -83.81, 24.22]}
          rotation={[2.62, 0, -Math.PI / 2]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.body_19.geometry}
          material={nodes.body_19.material}
          position={[20.1, -92.85, 6.17]}
          rotation={[-1.94, -Math.PI / 2, 0]}
          scale={[1, 1, 1]}
        />
        <mesh geometry={nodes.body_21.geometry} material={nodes.body_21.material} position={[16, 0, 64]} />
        <mesh
          geometry={nodes.body_23.geometry}
          material={nodes.body_23.material}
          position={[36.1, 3.9, 54.4]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.body_25.geometry}
          material={nodes.body_25.material}
          position={[44.1, 3.9, 44.8]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.body_27.geometry}
          material={nodes.body_27.material}
          position={[44.1, -3.9, 35.2]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.body_29.geometry}
          material={nodes.body_29.material}
          position={[36, 52.1, 48]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.body_31.geometry}
          material={nodes.body_31.material}
          position={[36, 20.1, 44.8]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh geometry={nodes.body_33.geometry} material={nodes.body_33.material} position={[24, 23.9, 44.8]} />
        <mesh geometry={nodes.body_35.geometry} material={nodes.body_35.material} position={[16, 24, 35.2]} />
        <mesh
          geometry={nodes.body_37.geometry}
          material={nodes.body_37.material}
          position={[12.2, 35.9, 12.8]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh geometry={nodes.body_39.geometry} material={nodes.body_39.material} position={[16, 56, 44.8]} />
        <mesh geometry={nodes.body_41.geometry} material={nodes.body_41.material} position={[24, 24, 22.4]} />
        <mesh geometry={nodes.body_43.geometry} material={nodes.body_43.material} position={[8, 0, 28.8]} />
        <mesh
          geometry={nodes.body_45.geometry}
          material={nodes.body_45.material}
          position={[1, -83.04, 10.55]}
          rotation={[2.78, -Math.PI / 2, 0]}
          scale={[1, 1, 1]}
        />
        <mesh geometry={nodes.body_47.geometry} material={nodes.body_47.material} position={[0.06, 20, 36.8]} />
        <mesh geometry={nodes.body_49.geometry} material={nodes.body_49.material} position={[16, -72.1, 0]} />
        <mesh geometry={nodes.body_51.geometry} material={nodes.body_51.material} position={[40, 0, 12.8]} />
        <mesh
          geometry={nodes.body_52_instance_0.geometry}
          material={nodes.body_52_instance_0.material}
          position={[36.2, 35.9, 12.8]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.body_52_instance_1.geometry}
          material={nodes.body_52_instance_1.material}
          position={[36.2, -28.1, 12.8]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.body_52_instance_2.geometry}
          material={nodes.body_52_instance_2.material}
          position={[12, -27.9, 12.8]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.body_53_instance_0.geometry}
          material={nodes.body_53_instance_0.material}
          position={[16, 7.9, 32]}
        />
        <mesh
          geometry={nodes.body_53_instance_1.geometry}
          material={nodes.body_53_instance_1.material}
          position={[16, -0.1, 32]}
        />
        <group position={[-3.9, 20.29, 35.22]} rotation={[0.12, 0, -Math.PI / 2]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.prt_1_12_SOLIDS_1.geometry} material={nodes.prt_1_12_SOLIDS_1.material} />
          <mesh geometry={nodes.prt_1_12_SOLIDS_1_1.geometry} material={nodes.prt_1_12_SOLIDS_1_1.material} />
          <mesh geometry={nodes.prt_1_12_SOLIDS_1_2.geometry} material={nodes.prt_1_12_SOLIDS_1_2.material} />
        </group>
        <group position={[52.1, -59.33, 25.61]} rotation={[0.12, 0, Math.PI / 2]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.prt_1_12_SOLIDS_3.geometry} material={nodes.prt_1_12_SOLIDS_3.material} />
          <mesh geometry={nodes.prt_1_12_SOLIDS_3_1.geometry} material={nodes.prt_1_12_SOLIDS_3_1.material} />
          <mesh geometry={nodes.prt_1_12_SOLIDS_3_2.geometry} material={nodes.prt_1_12_SOLIDS_3_2.material} />
        </group>
        <group position={[36.1, 44.1, 3.2]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.prt_1_16_SOLIDS_1.geometry} material={nodes.prt_1_16_SOLIDS_1.material} />
          <mesh geometry={nodes.prt_1_16_SOLIDS_1_1.geometry} material={nodes.prt_1_16_SOLIDS_1_1.material} />
          <mesh geometry={nodes.prt_1_16_SOLIDS_1_2.geometry} material={nodes.prt_1_16_SOLIDS_1_2.material} />
        </group>
        <group position={[12.1, 44.1, 3.2]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.prt_1_16_SOLIDS_3.geometry} material={nodes.prt_1_16_SOLIDS_3.material} />
          <mesh geometry={nodes.prt_1_16_SOLIDS_3_1.geometry} material={nodes.prt_1_16_SOLIDS_3_1.material} />
          <mesh geometry={nodes.prt_1_16_SOLIDS_3_2.geometry} material={nodes.prt_1_16_SOLIDS_3_2.material} />
        </group>
        <mesh
          geometry={nodes.body_54_instance_0.geometry}
          material={nodes.body_54_instance_0.material}
          position={[-3.9, 3.9, 3.2]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.body_54_instance_1.geometry}
          material={nodes.body_54_instance_1.material}
          position={[52.1, 3.9, 3.2]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.body_55_instance_0.geometry}
          material={nodes.body_55_instance_0.material}
          position={[44, 4.1, 32]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.body_55_instance_1.geometry}
          material={nodes.body_55_instance_1.material}
          position={[4, 4.1, 32]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.body_55_instance_2.geometry}
          material={nodes.body_55_instance_2.material}
          position={[24, 23.9, 32]}
        />
        <mesh
          geometry={nodes.body_55_instance_3.geometry}
          material={nodes.body_55_instance_3.material}
          position={[24, 23.9, 19.2]}
        />
        <mesh
          geometry={nodes.body_55_instance_4.geometry}
          material={nodes.body_55_instance_4.material}
          position={[36.2, 19.9, 28.8]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.body_55_instance_5.geometry}
          material={nodes.body_55_instance_5.material}
          position={[12.2, 19.9, 28.8]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.body_55_instance_6.geometry}
          material={nodes.body_55_instance_6.material}
          position={[24, -72.1, 6.4]}
        />
        <mesh
          geometry={nodes.body_55_instance_7.geometry}
          material={nodes.body_55_instance_7.material}
          position={[24, -72.1, 3.2]}
        />
        <mesh
          geometry={nodes.body_55_instance_8.geometry}
          material={nodes.body_55_instance_8.material}
          position={[12, 4.1, 16]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.body_55_instance_9.geometry}
          material={nodes.body_55_instance_9.material}
          position={[36, 4.1, 16]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.body_56.geometry}
          material={nodes.body_56.material}
          position={[12, 20.1, 44.8]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.body_57_instance_0.geometry}
          material={nodes.body_57_instance_0.material}
          position={[16, -16, 22.4]}
        />
        <mesh
          geometry={nodes.body_57_instance_1.geometry}
          material={nodes.body_57_instance_1.material}
          position={[16, -16, 12.8]}
        />
        <mesh
          geometry={nodes.body_57_instance_2.geometry}
          material={nodes.body_57_instance_2.material}
          position={[36.1, 20.1, 19.2]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.body_57_instance_3.geometry}
          material={nodes.body_57_instance_3.material}
          position={[12.1, 20.1, 19.2]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.body_58_instance_0.geometry}
          material={nodes.body_58_instance_0.material}
          position={[16, 23.9, 16]}
        />
        <mesh
          geometry={nodes.body_58_instance_1.geometry}
          material={nodes.body_58_instance_1.material}
          position={[16, 23.9, 12.8]}
        />
        <group position={[44.1, 18.4, 36.9]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes.prt_1_6_SOLIDS_1.geometry} material={nodes.prt_1_6_SOLIDS_1.material} />
          <mesh geometry={nodes.prt_1_6_SOLIDS_1_1.geometry} material={nodes.prt_1_6_SOLIDS_1_1.material} />
        </group>
        <group position={[4.1, 18.4, 4.7]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.prt_1_6_SOLIDS_3.geometry} material={nodes.prt_1_6_SOLIDS_3.material} />
          <mesh geometry={nodes.prt_1_6_SOLIDS_3_1.geometry} material={nodes.prt_1_6_SOLIDS_3_1.material} />
        </group>
        <mesh
          geometry={nodes.body_59_instance_0.geometry}
          material={nodes.body_59_instance_0.material}
          position={[12, 52.1, 48]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.body_59_instance_1.geometry}
          material={nodes.body_59_instance_1.material}
          position={[36.2, 19.9, 32]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.body_59_instance_2.geometry}
          material={nodes.body_59_instance_2.material}
          position={[12.2, 19.9, 32]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.body_59_instance_3.geometry}
          material={nodes.body_59_instance_3.material}
          position={[8, -16.1, 32]}
        />
        <mesh geometry={nodes.body_60.geometry} material={nodes.body_60.material} position={[40, 0, 28.8]} />
        <mesh geometry={nodes.body_61.geometry} material={nodes.body_61.material} position={[0, 0, 12.8]} />
        <mesh
          geometry={nodes.body_62_instance_0.geometry}
          material={nodes.body_62_instance_0.material}
          position={[16, 0, 51.2]}
        />
        <mesh
          geometry={nodes.body_62_instance_1.geometry}
          material={nodes.body_62_instance_1.material}
          position={[28.1, 3.9, 48]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.body_62_instance_2.geometry}
          material={nodes.body_62_instance_2.material}
          position={[16, -56, 12.8]}
        />
        <group position={[0, 48, 28.8]}>
          <mesh geometry={nodes.prt_2_8_t_SOLIDS_1.geometry} material={nodes.prt_2_8_t_SOLIDS_1.material} />
          <mesh geometry={nodes.prt_2_8_t_SOLIDS_1_1.geometry} material={nodes.prt_2_8_t_SOLIDS_1_1.material} />
        </group>
        <mesh geometry={nodes.prt_2_8_t_SOLIDS_1.geometry} material={nodes.prt_2_8_t_SOLIDS_1.material} />
        <mesh geometry={nodes.prt_2_8_t_SOLIDS_1_1.geometry} material={nodes.prt_2_8_t_SOLIDS_1_1.material} />
        <group position={[0, 48, 51.2]}>
          <mesh geometry={nodes.prt_2_8_t_SOLIDS_4.geometry} material={nodes.prt_2_8_t_SOLIDS_4.material} />
          <mesh geometry={nodes.prt_2_8_t_SOLIDS_4_1.geometry} material={nodes.prt_2_8_t_SOLIDS_4_1.material} />
        </group>
        <mesh
          geometry={nodes.body_63.geometry}
          material={nodes.body_63.material}
          position={[4.1, -3.9, 35.2]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.body_64_instance_0.geometry}
          material={nodes.body_64_instance_0.material}
          position={[4, -75.01, 39.46]}
          rotation={[-Math.PI / 6, 0, -Math.PI / 2]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.body_64_instance_1.geometry}
          material={nodes.body_64_instance_1.material}
          position={[-12, -57.82, 50.63]}
          rotation={[1.68, 0, Math.PI / 2]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.body_64_instance_2.geometry}
          material={nodes.body_64_instance_2.material}
          position={[-4.52, -8.19, 63.37]}
          rotation={[-1.48, 0, Math.PI]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.body_64_instance_3.geometry}
          material={nodes.body_64_instance_3.material}
          position={[6.98, 4.66, 48.43]}
          rotation={[-1.48, -Math.PI / 2, 0]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.body_64_instance_4.geometry}
          material={nodes.body_64_instance_4.material}
          position={[52.72, -8.19, 63.37]}
          rotation={[-1.48, 0, Math.PI]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.body_64_instance_5.geometry}
          material={nodes.body_64_instance_5.material}
          position={[41.22, 4.66, 48.43]}
          rotation={[-1.48, Math.PI / 2, 0]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.body_64_instance_6.geometry}
          material={nodes.body_64_instance_6.material}
          position={[60.32, -57.82, 50.63]}
          rotation={[1.68, 0, -Math.PI / 2]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.body_64_instance_7.geometry}
          material={nodes.body_64_instance_7.material}
          position={[44.32, -75.01, 39.46]}
          rotation={[-Math.PI / 6, 0, Math.PI / 2]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.body_65.geometry}
          material={nodes.body_65.material}
          position={[-11.2, -83.81, 24.22]}
          rotation={[2.62, 0, Math.PI / 2]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.body_66_instance_0.geometry}
          material={nodes.body_66_instance_0.material}
          position={[27.97, -92.85, 6.17]}
          rotation={[-1.94, Math.PI / 2, 0]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.body_66_instance_1.geometry}
          material={nodes.body_66_instance_1.material}
          position={[-7.5, -97.23, 15.98]}
          rotation={[2.78, -Math.PI / 2, 0]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.body_66_instance_2.geometry}
          material={nodes.body_66_instance_2.material}
          position={[55.82, -87.42, 20.37]}
          rotation={[1.21, Math.PI / 2, 0]}
          scale={[1, 1, 1]}
        />
        <group position={[8, 8, 35.2]}>
          <mesh geometry={nodes.technic_1_1_p_SOLIDS_1.geometry} material={nodes.technic_1_1_p_SOLIDS_1.material} />
          <mesh geometry={nodes.technic_1_1_p_SOLIDS_1_1.geometry} material={nodes.technic_1_1_p_SOLIDS_1_1.material} />
        </group>
        <group position={[12.1, 59.9, 35.2]} rotation={[0, 0, Math.PI / 2]}>
          <mesh geometry={nodes.technic_1_1_p_SOLIDS_1.geometry} material={nodes.technic_1_1_p_SOLIDS_1.material} />
          <mesh geometry={nodes.technic_1_1_p_SOLIDS_1_1.geometry} material={nodes.technic_1_1_p_SOLIDS_1_1.material} />
        </group>
        <group position={[36.1, 59.9, 35.2]} rotation={[0, 0, Math.PI / 2]}>
          <mesh geometry={nodes.technic_1_1_p_SOLIDS_1.geometry} material={nodes.technic_1_1_p_SOLIDS_1.material} />
          <mesh geometry={nodes.technic_1_1_p_SOLIDS_1_1.geometry} material={nodes.technic_1_1_p_SOLIDS_1_1.material} />
        </group>
        <group position={[48, 8, 35.2]}>
          <mesh geometry={nodes.technic_1_1_p_SOLIDS_5.geometry} material={nodes.technic_1_1_p_SOLIDS_5.material} />
          <mesh geometry={nodes.technic_1_1_p_SOLIDS_5_1.geometry} material={nodes.technic_1_1_p_SOLIDS_5_1.material} />
        </group>
        <mesh
          geometry={nodes.body_67.geometry}
          material={nodes.body_67.material}
          position={[36.1, 59.9, 44.8]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <group position={[52.2, 51.9, 48]} rotation={[0, 0, Math.PI / 2]}>
          <mesh
            geometry={nodes.technic_1_2_side_p_SOLIDS_1.geometry}
            material={nodes.technic_1_2_side_p_SOLIDS_1.material}
          />
          <mesh
            geometry={nodes.technic_1_2_side_p_SOLIDS_1_1.geometry}
            material={nodes.technic_1_2_side_p_SOLIDS_1_1.material}
          />
        </group>
        <group position={[-4, 52.1, 48]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh
            geometry={nodes.technic_1_2_side_p_SOLIDS_3.geometry}
            material={nodes.technic_1_2_side_p_SOLIDS_3.material}
          />
          <mesh
            geometry={nodes.technic_1_2_side_p_SOLIDS_3_1.geometry}
            material={nodes.technic_1_2_side_p_SOLIDS_3_1.material}
          />
        </group>
        <mesh
          geometry={nodes.body_68.geometry}
          material={nodes.body_68.material}
          position={[12.1, 3.9, 54.4]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh geometry={nodes.body_69.geometry} material={nodes.body_69.material} position={[8, 0, 44.8]} />
        <group position={[24, -72.1, 9.6]}>
          <mesh
            geometry={nodes.technic_bump_support_p_SOLIDS_1.geometry}
            material={nodes.technic_bump_support_p_SOLIDS_1.material}
          />
          <mesh
            geometry={nodes.technic_bump_support_p_SOLIDS_1_1.geometry}
            material={nodes.technic_bump_support_p_SOLIDS_1_1.material}
          />
        </group>
        <mesh
          geometry={nodes.body_70_instance_0.geometry}
          material={nodes.body_70_instance_0.material}
          position={[47.32, -83.04, 10.55]}
          rotation={[2.78, Math.PI / 2, 0]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.body_70_instance_1.geometry}
          material={nodes.body_70_instance_1.material}
          position={[7.4, -62.25, 19.84]}
          rotation={[1.21, Math.PI / 2, 0]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.body_70_instance_2.geometry}
          material={nodes.body_70_instance_2.material}
          position={[40.92, -62.25, 19.84]}
          rotation={[1.21, -Math.PI / 2, 0]}
          scale={[1, 1, 1]}
        />
        <group position={[-15.98, -94.37, 5.38]} rotation={[2.78, Math.PI / 2, 0]} scale={[1, 1, 1]}>
          <mesh
            geometry={nodes.technic_shaft_x10_SOLIDS_1.geometry}
            material={nodes.technic_shaft_x10_SOLIDS_1.material}
          />
          <mesh
            geometry={nodes.technic_shaft_x10_SOLIDS_1_1.geometry}
            material={nodes.technic_shaft_x10_SOLIDS_1_1.material}
          />
        </group>
        <group position={[50.78, -94.83, 22.91]} rotation={[-Math.PI / 6, 0, Math.PI / 2]} scale={[1, 1, 1]}>
          <mesh
            geometry={nodes.technic_shaft_x4_SOLIDS_1.geometry}
            material={nodes.technic_shaft_x4_SOLIDS_1.material}
          />
          <mesh
            geometry={nodes.technic_shaft_x4_SOLIDS_1_1.geometry}
            material={nodes.technic_shaft_x4_SOLIDS_1_1.material}
          />
        </group>
        <group position={[-4.74, -94.83, 22.91]} rotation={[-Math.PI / 6, 0, Math.PI / 2]} scale={[1, 1, 1]}>
          <mesh
            geometry={nodes.technic_shaft_x4_SOLIDS_1.geometry}
            material={nodes.technic_shaft_x4_SOLIDS_1.material}
          />
          <mesh
            geometry={nodes.technic_shaft_x4_SOLIDS_1_1.geometry}
            material={nodes.technic_shaft_x4_SOLIDS_1_1.material}
          />
        </group>
        <group position={[32.75, -70.73, 44.61]} rotation={[2.62, 0, -Math.PI]} scale={[1, 1, 1]}>
          <mesh
            geometry={nodes.technic_shaft_x4_SOLIDS_4.geometry}
            material={nodes.technic_shaft_x4_SOLIDS_4.material}
          />
          <mesh
            geometry={nodes.technic_shaft_x4_SOLIDS_4_1.geometry}
            material={nodes.technic_shaft_x4_SOLIDS_4_1.material}
          />
        </group>
        <group position={[43.84, -64.32, 48.8]} rotation={[-1.47, 0, 0]} scale={[1, 1, 1]}>
          <mesh
            geometry={nodes.technic_shaft_x8_SOLIDS_1.geometry}
            material={nodes.technic_shaft_x8_SOLIDS_1.material}
          />
          <mesh
            geometry={nodes.technic_shaft_x8_SOLIDS_1_1.geometry}
            material={nodes.technic_shaft_x8_SOLIDS_1_1.material}
          />
        </group>
        <group position={[-13.28, -64.32, 48.8]} rotation={[-1.47, 0, 0]} scale={[1, 1, 1]}>
          <mesh
            geometry={nodes.technic_shaft_x8_SOLIDS_3.geometry}
            material={nodes.technic_shaft_x8_SOLIDS_3.material}
          />
          <mesh
            geometry={nodes.technic_shaft_x8_SOLIDS_3_1.geometry}
            material={nodes.technic_shaft_x8_SOLIDS_3_1.material}
          />
        </group>
        <mesh
          geometry={nodes.body_71_instance_0.geometry}
          material={nodes.body_71_instance_0.material}
          position={[27.97, -90.14, 13.27]}
          rotation={[2.78, -Math.PI / 2, 0]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.body_72_instance_0.geometry}
          material={nodes.body_72_instance_0.material}
          position={[40.22, 4, 56]}
          rotation={[-1.48, 0, Math.PI]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.body_72_instance_1.geometry}
          material={nodes.body_72_instance_1.material}
          position={[48.02, -59.53, 26.94]}
          rotation={[-1.94, 0, 0]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.body_72_instance_2.geometry}
          material={nodes.body_72_instance_2.material}
          position={[0.3, -59.53, 26.94]}
          rotation={[1.21, 0, Math.PI]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.body_72_instance_3.geometry}
          material={nodes.body_72_instance_3.material}
          position={[7.98, -68, 4.8]}
          rotation={[1.21, 0, 0]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.body_72_instance_4.geometry}
          material={nodes.body_72_instance_4.material}
          position={[40.22, -68, 4.8]}
          rotation={[-1.94, 0, Math.PI]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.body_73_instance_0.geometry}
          material={nodes.body_73_instance_0.material}
          position={[48.14, 20, 36.8]}
        />
        <mesh
          geometry={nodes.body_73_instance_1.geometry}
          material={nodes.body_73_instance_1.material}
          position={[40.14, 20, 20.8]}
        />
        <mesh
          geometry={nodes.body_73_instance_2.geometry}
          material={nodes.body_73_instance_2.material}
          position={[40.14, 20, 4.8]}
        />
        <mesh
          geometry={nodes.body_73_instance_3.geometry}
          material={nodes.body_73_instance_3.material}
          position={[8.06, 20, 20.8]}
        />
        <mesh
          geometry={nodes.body_73_instance_4.geometry}
          material={nodes.body_73_instance_4.material}
          position={[8.06, 20, 4.8]}
        />
        <mesh
          geometry={nodes.body_74_instance_0.geometry}
          material={nodes.body_74_instance_0.material}
          position={[-4.52, 3.64, 60.13]}
          rotation={[-3.05, 0, 0]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.body_74_instance_1.geometry}
          material={nodes.body_74_instance_1.material}
          position={[-7.75, -69.26, 49.42]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes.body_74_instance_2.geometry}
          material={nodes.body_74_instance_2.material}
          position={[56.07, -69.26, 49.42]}
          rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        />
        <group position={[36.1, 51.9, 19.2]} rotation={[0, 0, Math.PI / 2]}>
          <mesh geometry={nodes.x_prt_1_2_a_u_SOLIDS_1.geometry} material={nodes.x_prt_1_2_a_u_SOLIDS_1.material} />
          <mesh geometry={nodes.x_prt_1_2_a_u_SOLIDS_1_1.geometry} material={nodes.x_prt_1_2_a_u_SOLIDS_1_1.material} />
        </group>
        <group position={[12.1, 51.9, 19.2]} rotation={[0, 0, Math.PI / 2]}>
          <mesh geometry={nodes.x_prt_1_2_a_u_SOLIDS_3.geometry} material={nodes.x_prt_1_2_a_u_SOLIDS_3.material} />
          <mesh geometry={nodes.x_prt_1_2_a_u_SOLIDS_3_1.geometry} material={nodes.x_prt_1_2_a_u_SOLIDS_3_1.material} />
        </group>
      </group>
      <PerspectiveCamera
        makeDefault={false}
        far={2000000}
        near={0.1}
        fov={45}
        position={[-8.86, 4.49, 12.81]}
        rotation={[-0.33, -0.63, -0.2]}>
        <directionalLight intensity={0.25} decay={2} color="#ffeedd" position={[-8.25, 4.12, 4.12]} />
      </PerspectiveCamera>
      <directionalLight
        intensity={0.32}
        decay={2}
        color="#ffeedd"
        position={[-8.38, 16.76, -6.01]}
        rotation={[-2.03, -0.42, -0.67]}
        scale={[0, 0, 8.33]}
      />
    </group>
  )
}

useGLTF.preload('/Buggy.gltf')
