/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/DOC.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.streetscapes_for_wellness002.geometry}
        material={materials.diffuse_0_0_0_255}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0}
      />
            <PerspectiveCamera
        makeDefault={false}
        far={2000000}
        near={0.1}
        fov={45}
        position={[-8.86, 4.49, 12.81]}
        rotation={[-0.33, -0.63, -0.2]}>
        <directionalLight intensity={0.25} decay={2} color="#ffeedd" position={[-8.25, 4.12, 4.12]} />
      </PerspectiveCamera>
      <directionalLight
        intensity={0.32}
        decay={2}
        color="#ffeedd"
        position={[-8.38, 16.76, -6.01]}
        rotation={[-2.03, -0.42, -0.67]}
        scale={[0, 0, 8.33]}
      />

    </group>
  )
}

useGLTF.preload('/DOC.gltf')
